### PR TITLE
Feature/junit results

### PR DESCRIPTION
**Pull request by daldinger**
Based on changes in PR #33. Produces junit report results from the fitnesse results. Important note, changes for JEP 200 (PR #35) must also be delivered with any new version of this plugin, else builds will not be serialized.

### CODE REVIEW

**Comment by neshp** [comment]
@jaruzafa @lessonz  when can I expect this pull request to be merged to master?

**Comment by lessonz** [comment]
Sorry @neshp, I'm no longer involved with this project.

**Comment by jaruzafa** [comment]
Hi @nesp, I’m still catching up some issues in other PRs. As soon as I fix them I’ll proceed with this one. Cheers!

**Comment by pranay230** [comment]
Hi @jaruzafa,
When can we expect this, this would be really great a feature.

Thanks,
PS

**Pull request merged**
