### PR TITLE
Feature/pipeline compatibility

### PR DESCRIPTION
**Pull request by raymondwu1**
Adds pipeline compatibility to the Fitnesse plugin
Thanks to eplatti for fixing the findbugs issues

### CODE REVIEW

**Comment by childnode** [comment]
unfortunatly this code has not been published yet : https://issues.jenkins-ci.org/browse/JENKINS-41514 > https://issues.jenkins-ci.org/browse/JENKINS-40165

**Comment by lessonz** [comment]
Unfortunately, I haven't used FitNesse in years. If someone would like to request commit access, you're welcome to do so. I did the same myself years ago because I needed a fix for this repo. Unfortunately, a quick search doesn't turn up the link for requesting that access. The wiki lists timbacon as the maintainer, and maybe that's true.

If you're interested and motivated, I welcome you to request committer access so you can handle pushing a new release. In 2014, it looks like I did that via the maven-release-plugin. I wish you the best of luck.

**Comment by jaruzafa** [comment]
Hi @lessonz , 
I really need this feature for my pipeline. Please, could you give me commit acces so I can release a new version?
Thanks!

**Comment by lessonz** [comment]
First, to get you unblocked, I suggest you build a local copy and install it. I've done this myself in the past.

Second, I am no longer involved with this plugin, please see: https://groups.google.com/forum/#!topic/jenkinsci-dev/II-ishc_xfU

I do not have permissions to grant any rights on this repo. I haven't used FitNesse in years. I'm sorry I couldn't be more help.

**Comment by muriloht** [comment]
hi @jaruzafa do you have some sample of how you did your fitnesse run into your pipeline? tks!

**Comment by jaruzafa** [comment]
Sure!
You can use the Pipeline Syntax helper to generate the commands. Go to _Pipeline Syntax -> Step: General Build Step -> Execute Fitnesse tests and PublishFitNesse Results._

**Example:**
Executing your suite:
```groovy
step([$class: 'FitnesseBuilder', options: [fitnessePathToRoot: 'fitnesse/FitNesseRoot', additionalFitnesseOptions: '', fitnesseTestTimeout: '', fitnesseStart: 'True', fitnesseHttpTimeout: '', fitnesseTargetIsSuite: 'true', fitnesseJavaOpts: '', fitnessePathToJar: 'fitnesse/fitnesse-standalone.jar', fitnesseTargetPage: 'MyTestSuite', fitnessePathToXmlResultsOut: 'results.xml', fitnessePortLocal: '8080', fitnesseJavaWorkingDirectory: '']]) 
```

Publishing the results:
```groovy
step([$class: 'FitnesseResultsRecorder', fitnessePathToXmlResultsIn: 'results.xml'])
```

**Comment by muriloht** [comment]
Thank you @jaruzafa ! :)

**Pull request merged**
